 plugins {
    id 'java-library'
    id 'eclipse'
    id 'idea'
    id 'maven-publish'
    id 'net.neoforged.gradle.userdev' version '7.0.173'
}

version = minecraft_version + "-" + mod_version
group = mod_group_id
java.toolchain.languageVersion = JavaLanguageVersion.of(21)
minecraft.accessTransformers.file rootProject.file('src/main/resources/META-INF/accesstransformer.cfg')

base {
    archivesName = mod_id
}

repositories {
    maven {
        url "https://cursemaven.com"
        content { includeGroup "curse.maven" }
    }
    maven {
        name = "Jared's maven"
        url = "https://maven.blamejared.com/"
    }
    maven {
        name = "ModMaven"
        url = "https://modmaven.dev"
    }
    maven { url = "https://api.modrinth.com/maven" }
    maven { url = "https://maven.neoforged.net/releases" }
    maven { url = 'https://repo.spongepowered.org/repository/maven-public/' }
    mavenCentral()
    jcenter()
    flatDir {
        dir 'libs'
    }
}

configurations {
    runtimeClasspath.extendsFrom localRuntime
}

dependencies {
    implementation "net.neoforged:neoforge:${neo_version}"
    // compileOnly "org.spongepowered:mixin:0.8.5"

    // Imports
    // Dependencies
    implementation "curse.maven:accessories-${accessories_version}" // Requires Owo Lib, Required Dependency
    implementation "curse.maven:accessories-compat-layer-1315611:7585673" // Requires Accessories, Curios, Owo Lib
    implementation "curse.maven:ctm-${ctm_version}" // Optional Dependency
    implementation "curse.maven:curios-309927:6529130"
    implementation "curse.maven:every-compat-${every_compat_version}" // Requires Moonlight, Optional Dependency
    implementation "curse.maven:fusion-connected-textures-${fusion_version}" // Optional Dependency
    implementation "curse.maven:geckolib-${geckolib_version}" // Required Dependency
    implementation "curse.maven:mmmmmmmmmmmm-${test_dummy_version}" // Requires Moonlight, Optional Dependency
    implementation "curse.maven:stone-zone-${stone_zone_version}" // Requires Moonlight, Optional Dependency
    compileOnly "curse.maven:supplementaries-${supplementaries_version}" // Requires Moonlight, Optional Dependency

    implementation "curse.maven:aether-255308:6389857"
    implementation "curse.maven:amendments-896746:7352178" // Requires Moonlight
    compileOnly "maven.modrinth:automobility:0.5.0.h-neoforge" // Requires Kotlin
    implementation "curse.maven:copycats-968398:6650033" // Requires Create
    implementation "curse.maven:create-328085:6641610"
    implementation "curse.maven:deep-aether-852465:6839619"
    implementation "curse.maven:embeddium-${embeddium_version}"
    implementation "curse.maven:gardens-of-the-dead-683174:5640395"
    implementation "curse.maven:guard-villagers-360203:6066966"
    compileOnly "curse.maven:immersive-paintings-639584:7583940" // Requires Fzzy Config
    implementation "curse.maven:inspectability-1312917:6805145"
    compileOnly "curse.maven:irisshaders-455508:6661598" // Requires Sodium
    implementation "curse.maven:jade-324717:6853386"
    implementation "curse.maven:neoculus-1200907:6787071"
    implementation "curse.maven:refurbished-furniture-897116:7473565" // Requires Framework
    implementation "curse.maven:roughly-enough-items-${rei_version}"
    implementation "curse.maven:spark-${spark_version}"
    implementation "curse.maven:the-twilight-forest-227639:7797302"
    implementation "curse.maven:vista-${vista_version}" // Requires Moonlight
    implementation "curse.maven:worldedit-225608:5830452"
    implementation "curse.maven:xaeros-minimap-263420:6778051"
    implementation "curse.maven:xaeros-world-map-317780:6778114"

    // Libraries
    implementation "curse.maven:architectury-api-${architectury_api_version}"
    implementation "curse.maven:cloth-config-${cloth_config_version}"
    implementation "curse.maven:kotlin-for-forge-351264:7471280"
    implementation "curse.maven:framework-549225:7530361"
    compileOnly "curse.maven:fzzy-config-1005914:7568897"
    implementation "curse.maven:owo-lib-${owo_version}"
    implementation "curse.maven:selene-${moonlight_version}"
    compileOnly "curse.maven:sodium-394468:6382651" // Incompatible w/ Embeddium

    // implementation "curse.maven:simple-clouds-${simple_clouds_version}"

    // implementation "com.github.Virtuoel:Pehkui:${pehkui_version}"
    // implementation "software.bernie.geckolib:geckolib-neoforge-${minecraft_version}:${geckolib_version}"

    // implementation "curse.maven:itemzoom-261725:5536959"
    compileOnly "curse.maven:jei-${jei_version}"
    implementation "mezz.jei:jei-${minecraft_version}-neoforge-api:${jei_spef_version}"
    // implementation "curse.maven:pehkui-${pehkui_version}"
    // implementation "curse.maven:structure-gel-api-${structure_gel_version}"
}


runs {
    configureEach {
        systemProperty 'forge.logging.markers', 'REGISTRIES'
        systemProperty 'forge.logging.console.level', 'debug'
        programArguments '-mixin.config=marioverse.mixins.json'

        modSource project.sourceSets.main
    }

    client {
        workingDirectory 'run'
        client true
        server false
        dataGenerator false
        gameTest false
        systemProperty 'forge.enabledGameTestNamespaces', project.mod_id
        programArguments.addAll '--username', 'WenXin2'
    }

    server {
        workingDirectory 'run'
        client false
        server true
        dataGenerator false
        gameTest false
        systemProperty 'forge.enabledGameTestNamespaces', project.mod_id
    }

    gameTestServer {
        workingDirectory 'run'
        client false
        server false
        dataGenerator false
        gameTest true
        systemProperty 'forge.enabledGameTestNamespaces', project.mod_id
    }

    data {
        workingDirectory 'run'
        client false
        server false
        dataGenerator true
        gameTest false
        systemProperty 'forge.enabledGameTestNamespaces', project.mod_id
        programArguments.addAll '--mod', 'marioverse', '--all', '--output',
                file('src/generated/resources/').getAbsolutePath(), '--existing', file('src/main/resources/').getAbsolutePath()
    }
}

// Include resources generated by data generators.
sourceSets.main.resources { srcDir 'src/generated/resources' }

println "Java: ${System.getProperty 'java.version'}, JVM: ${System.getProperty 'java.vm.version'} (${System.getProperty 'java.vendor'}), Arch: ${System.getProperty 'os.arch'}"

tasks.withType(ProcessResources).configureEach {
    var replaceProperties = [
            minecraft_version       : minecraft_version,
            minecraft_version_range : minecraft_version_range,
            neo_version             : neo_version,
            neo_version_range       : neo_version_range,
            loader_version_range    : loader_version_range,
            mod_id                  : mod_id,
            mod_name                : mod_name,
            mod_license             : mod_license,
            mod_version             : mod_version,
            mod_authors             : mod_authors,
            mod_description         : mod_description,
            mixin_configs           : mixin_location
    ]
    inputs.properties replaceProperties

    filesMatching(['META-INF/neoforge.mods.toml', '*.mixins.json']) {
        expand replaceProperties
    }
}

publishing {
    publications {
        register('mavenJava', MavenPublication) {
            from components.java
        }
    }

    repositories {
        maven {
            url "file://${project.projectDir}/repo"
        }

//        maven {
//            name = 'GeckoLib'
//            url 'https://dl.cloudsmith.io/public/geckolib3/geckolib/maven/'
//            content {
//                includeGroup("software.bernie.geckolib")
//            }
//        }
//        maven {
//            url = "https://jitpack.io"
//        }
    }
}

 tasks.withType(JavaCompile).configureEach {
     options.encoding = 'UTF-8' // Use the UTF-8 charset for Java compilation
 }

 tasks.withType(Copy).configureEach {
     duplicatesStrategy = DuplicatesStrategy.INCLUDE
 }

idea {
    module {
        downloadSources = true
        downloadJavadoc = true
    }
}
