# Sets default memory used for gradle commands. Can be overridden by user or command line properties.
# This is required to provide enough memory for the Minecraft decompilation process.
org.gradle.jvmargs=-Xms6G
org.gradle.daemon=false

neo_version=21.1.205
neo_version_range=[21.1.181,)
loader_version_range=[4,)
minecraft_version=1.21.1
minecraft_version_range=[1.21,1.21.1)

mod_id=marioverse
mod_name=WenXin's Marioverse
mod_version=1.0.5-neoforge
mod_group_id=com.wenxin2.marioverse
mod_license=GNU GPLv3
mod_authors=WenXin2
mod_description=This mod adds new blocks, items, and mobs from the Mario universe!
mixin_location=marioverse.mixins.json

ctm_version_range=[1.2.0,)
fusion_version_range=[1.1.1+a,)
geckolib_version_range=[4.6,)
pehkui_version_range=[3.8.3+1.21-neoforge,)

accessories_version=938917:6006110
architectury_api_version=419699:5786327
cloth_config_version=348521:5729127
ctm_version=267602:5587515
embeddium_version=908741:6118392
every_compat_version=628539:6961448
fusion_version=854949:6826913
geckolib_version=388172:6920810
jei_version=238222:5846880
moonlight_version=499980:6960423
owo_version=532610:5945693
pehkui_version=319596:5446174
rei_version=310111:5846953
simple_clouds_version=1121215:5812034
sodium_version=394468:6211307
stone_zone_version=1154622:6964339
spark_version=361579:5759671
structure_gel_version=378802:5391404
supplementaries_version=412082:6707170
test_dummy_version=225738:6237115

# connectedness_version=853916:4506203
# reforgium_version=853424:4505759