# Find more information on toml format here:  https://github.com/toml-lang/toml
# The name of the mod loader type to load - for regular FML @Mod mods it should be javafml
modLoader="javafml"
# A version range to match for said mod loader - for regular FML @Mod it will be the forge version
loaderVersion="${loader_version_range}"
# The license for you mod.
license="${mod_license}"
# A URL to refer people to when problems occur with this mod
issueTrackerURL="https://github.com/WenXin20/Marioverse/issues"

# A list of mods - how many allowed here is determined by the individual mod loader
[[mods]]
# The modid of the mod
modId="marioverse"
# The version number of the mod
version="${minecraft_version}-${mod_version}"
# A display name for the mod
displayName="${mod_name}"
# A URL for the "homepage" for this mod, displayed in the mod UI
displayURL="https://github.com/WenXin20/Marioverse" #optional
# A file name (in the root of the mod JAR) containing a logo for display
logoFile="marioverse_banner.png"
# A text field displayed in the mod UI
credits="Made by WenXin2"
# A text field displayed in the mod UI
authors="${mod_authors}"

# The description text for the mod (multi line!) (#mandatory)
description='''${mod_description}'''

[[accessTransformers]]
file="META-INF/accesstransformer.cfg"

[[mixins]]
config="marioverse.mixins.json"

# A dependency - use the . to indicate dependency for a specific modid. Dependencies are optional.
[[dependencies.marioverse]] #optional
# the modid of the dependency
modId="neoforge"
# The type of the dependency. Can be one of "required", "optional", "incompatible" or "discouraged" (case insensitive).
# 'required' requires the mod to exist, 'optional' does not
# 'incompatible' will prevent the game from loading when the mod exists, and 'discouraged' will show a warning
type="required"
# The version range of the dependency
versionRange="${neo_version_range}"
# An ordering relationship for the dependency - BEFORE or AFTER required if the relationship is not mandatory
ordering="NONE"
# Side this dependency is applied on - BOTH, CLIENT or SERVER
side="BOTH"

[[dependencies.marioverse]]
modId="minecraft"
type="required"
versionRange="${minecraft_version_range}"
ordering="NONE"
side="BOTH"

[[dependencies.marioverse]]
modId="accessories"
type="required"
versionRange="[1.0.0-beta.31,)"
ordering="NONE"
side="CLIENT"

[[dependencies.marioverse]]
modId="geckolib"
type="required"
versionRange="[4.6,)"
ordering="NONE"
side="CLIENT"

[[dependencies.marioverse]]
modId="pehkui"
type="required"
versionRange="[3.8.3+1.21-neoforge,)"
ordering="NONE"
side="BOTH"

[[dependencies.marioverse]]
modId="ctm"
type="optional"
versionRange="[1.2.0,)"
ordering="AFTER"
side="CLIENT"

[[dependencies.marioverse]]
modId="fusion"
type="optional"
versionRange="[1.1.1+a,)"
ordering="AFTER"
side="CLIENT"
