package com.wenxin2.marioverse.datagen;

import com.wenxin2.marioverse.Marioverse;
import com.wenxin2.marioverse.init.BlockRegistry;
import com.wenxin2.marioverse.init.TagRegistry;
import java.util.concurrent.CompletableFuture;
import net.minecraft.core.HolderLookup;
import net.minecraft.data.PackOutput;
import net.minecraft.tags.BlockTags;
import net.neoforged.neoforge.common.data.BlockTagsProvider;
import net.neoforged.neoforge.common.data.ExistingFileHelper;

public class ModBlockTagsProvider extends BlockTagsProvider {
    public ModBlockTagsProvider(PackOutput output, CompletableFuture<HolderLookup.Provider> lookupProvider, ExistingFileHelper existingFileHelper) {
        super(output, lookupProvider, Marioverse.MOD_ID, existingFileHelper);
    }

    @Override
    @SuppressWarnings("unchecked")
    protected void addTags(HolderLookup.Provider lookupProvider) {
        tag(TagRegistry.BRICK_PEDESTAL_BLOCKS)
                .add(BlockRegistry.AMETHYST_BRICK_PEDESTAL.get())
                .add(BlockRegistry.BLACKSTONE_BRICK_PEDESTAL.get())
                .add(BlockRegistry.BRICK_PEDESTAL.get())
                .add(BlockRegistry.CUT_COPPER_PEDESTAL.get())
                .add(BlockRegistry.EXPOSED_CUT_COPPER_PEDESTAL.get())
                .add(BlockRegistry.DARK_PRISMARINE_PEDESTAL.get())
                .add(BlockRegistry.DEEP_FUNGAL_BRICK_PEDESTAL.get())
                .add(BlockRegistry.DEEPSLATE_BRICK_PEDESTAL.get())
                .add(BlockRegistry.DEEPSLATE_TILE_PEDESTAL.get())
                .add(BlockRegistry.END_STONE_BRICK_PEDESTAL.get())
                .add(BlockRegistry.FUNGAL_BRICK_PEDESTAL.get())
                .add(BlockRegistry.MOSSY_STONE_BRICK_PEDESTAL.get())
                .add(BlockRegistry.MUD_BRICK_PEDESTAL.get())
                .add(BlockRegistry.NETHER_BRICK_PEDESTAL.get())
                .add(BlockRegistry.PRISMARINE_BRICK_PEDESTAL.get())
                .add(BlockRegistry.PURPUR_BLOCK_PEDESTAL.get())
                .add(BlockRegistry.QUARTZ_BRICK_PEDESTAL.get())
                .add(BlockRegistry.RED_NETHER_BRICK_PEDESTAL.get())
                .add(BlockRegistry.STONE_BRICK_PEDESTAL.get())
                .add(BlockRegistry.TUFF_BRICK_PEDESTAL.get())
                .replace(false);

        tag(TagRegistry.INVISIBLE_QUESTION_BLOCKS)
                .add(BlockRegistry.INVISIBLE_AMETHYST_QUESTION_BLOCK.get())
                .add(BlockRegistry.INVISIBLE_BLACKSTONE_QUESTION_BRICKS.get())
                .add(BlockRegistry.INVISIBLE_QUESTION_BRICKS.get())
                .add(BlockRegistry.INVISIBLE_COPPER_QUESTION_BLOCK.get())
                .add(BlockRegistry.INVISIBLE_EXPOSED_COPPER_QUESTION_BLOCK.get())
                .add(BlockRegistry.INVISIBLE_DARK_PRISMARINE_QUESTION_BLOCK.get())
                .add(BlockRegistry.INVISIBLE_DEEP_FUNGAL_QUESTION_BLOCK.get())
                .add(BlockRegistry.INVISIBLE_DEEPSLATE_QUESTION_BRICKS.get())
                .add(BlockRegistry.INVISIBLE_DEEPSLATE_QUESTION_TILES.get())
                .add(BlockRegistry.INVISIBLE_END_STONE_QUESTION_BRICKS.get())
                .add(BlockRegistry.INVISIBLE_FUNGAL_QUESTION_BLOCK.get())
                .add(BlockRegistry.INVISIBLE_MOSSY_STONE_QUESTION_BRICKS.get())
                .add(BlockRegistry.INVISIBLE_MUD_QUESTION_BRICKS.get())
                .add(BlockRegistry.INVISIBLE_NETHER_QUESTION_BRICKS.get())
                .add(BlockRegistry.INVISIBLE_PRISMARINE_QUESTION_BRICKS.get())
                .add(BlockRegistry.INVISIBLE_PURPUR_QUESTION_BLOCK.get())
                .add(BlockRegistry.INVISIBLE_QUARTZ_QUESTION_BRICKS.get())
                .add(BlockRegistry.INVISIBLE_RED_NETHER_QUESTION_BRICKS.get())
                .add(BlockRegistry.INVISIBLE_STONE_QUESTION_BRICKS.get())
                .add(BlockRegistry.INVISIBLE_TUFF_QUESTION_BRICKS.get())
                .replace(false);

        tag(TagRegistry.QUESTION_BLOCKS)
                .add(BlockRegistry.AMETHYST_QUESTION_BLOCK.get())
                .add(BlockRegistry.BLACKSTONE_QUESTION_BRICKS.get())
                .add(BlockRegistry.QUESTION_BRICKS.get())
                .add(BlockRegistry.COPPER_QUESTION_BLOCK.get())
                .add(BlockRegistry.EXPOSED_COPPER_QUESTION_BLOCK.get())
                .add(BlockRegistry.DARK_PRISMARINE_QUESTION_BLOCK.get())
                .add(BlockRegistry.DEEP_FUNGAL_QUESTION_BLOCK.get())
                .add(BlockRegistry.DEEPSLATE_QUESTION_BRICKS.get())
                .add(BlockRegistry.DEEPSLATE_QUESTION_TILES.get())
                .add(BlockRegistry.END_STONE_QUESTION_BRICKS.get())
                .add(BlockRegistry.FUNGAL_QUESTION_BLOCK.get())
                .add(BlockRegistry.MOSSY_STONE_QUESTION_BRICKS.get())
                .add(BlockRegistry.MUD_QUESTION_BRICKS.get())
                .add(BlockRegistry.NETHER_QUESTION_BRICKS.get())
                .add(BlockRegistry.PRISMARINE_QUESTION_BRICKS.get())
                .add(BlockRegistry.PURPUR_QUESTION_BLOCK.get())
                .add(BlockRegistry.QUARTZ_QUESTION_BRICKS.get())
                .add(BlockRegistry.RED_NETHER_QUESTION_BRICKS.get())
                .add(BlockRegistry.STONE_QUESTION_BRICKS.get())
                .add(BlockRegistry.TUFF_QUESTION_BRICKS.get())
                .replace(false);

        tag(TagRegistry.SMASHABLE_BLOCKS)
                .add(BlockRegistry.AMETHYST_BRICK_PEDESTAL.get())
                .add(BlockRegistry.AMETHYST_BRICK_SLAB.get())
                .add(BlockRegistry.AMETHYST_BRICK_STAIRS.get())
                .add(BlockRegistry.AMETHYST_BRICK_WALL.get())
                .add(BlockRegistry.AMETHYST_BRICKS.get())
                .add(BlockRegistry.CHISELED_AMETHYST_BRICKS.get())
                .add(BlockRegistry.CRACKED_AMETHYST_BRICKS.get())
                .add(BlockRegistry.DEEP_FUNGAL_BRICK_PEDESTAL.get())
                .add(BlockRegistry.DEEP_FUNGAL_BRICK_SLAB.get())
                .add(BlockRegistry.DEEP_FUNGAL_BRICK_STAIRS.get())
                .add(BlockRegistry.DEEP_FUNGAL_BRICK_WALL.get())
                .add(BlockRegistry.DEEP_FUNGAL_BRICKS.get())
                .add(BlockRegistry.FUNGAL_BRICK_PEDESTAL.get())
                .add(BlockRegistry.FUNGAL_BRICK_SLAB.get())
                .add(BlockRegistry.FUNGAL_BRICK_STAIRS.get())
                .add(BlockRegistry.FUNGAL_BRICK_WALL.get())
                .add(BlockRegistry.FUNGAL_BRICKS.get())
                .add(BlockRegistry.SMASHABLE_BLACKSTONE_BRICKS.get())
                .add(BlockRegistry.SMASHABLE_BRICKS.get())
                .add(BlockRegistry.SMASHABLE_CUT_COPPER.get())
                .add(BlockRegistry.SMASHABLE_EXPOSED_CUT_COPPER.get())
                .add(BlockRegistry.SMASHABLE_DARK_PRISMARINE.get())
                .add(BlockRegistry.SMASHABLE_DEEPSLATE_BRICKS.get())
                .add(BlockRegistry.SMASHABLE_DEEPSLATE_TILES.get())
                .add(BlockRegistry.SMASHABLE_END_STONE_BRICKS.get())
                .add(BlockRegistry.SMASHABLE_MOSSY_STONE_BRICKS.get())
                .add(BlockRegistry.SMASHABLE_MUD_BRICKS.get())
                .add(BlockRegistry.SMASHABLE_NETHER_BRICKS.get())
                .add(BlockRegistry.SMASHABLE_PRISMARINE_BRICKS.get())
                .add(BlockRegistry.SMASHABLE_PURPUR_BLOCK.get())
                .add(BlockRegistry.SMASHABLE_QUARTZ_BRICKS.get())
                .add(BlockRegistry.SMASHABLE_RED_NETHER_BRICKS.get())
                .add(BlockRegistry.SMASHABLE_STONE_BRICKS.get())
                .add(BlockRegistry.SMASHABLE_TUFF_BRICKS.get())
                .replace(false);

        tag(TagRegistry.STORAGE_BRICK_BLOCKS)
                .add(BlockRegistry.STORAGE_AMETHYST_BRICKS.get())
                .add(BlockRegistry.STORAGE_BLACKSTONE_BRICKS.get())
                .add(BlockRegistry.STORAGE_BRICKS.get())
                .add(BlockRegistry.STORAGE_CUT_COPPER.get())
                .add(BlockRegistry.STORAGE_EXPOSED_CUT_COPPER.get())
                .add(BlockRegistry.STORAGE_DARK_PRISMARINE.get())
                .add(BlockRegistry.STORAGE_DEEP_FUNGAL_BRICKS.get())
                .add(BlockRegistry.STORAGE_DEEPSLATE_BRICKS.get())
                .add(BlockRegistry.STORAGE_DEEPSLATE_TILES.get())
                .add(BlockRegistry.STORAGE_END_STONE_BRICKS.get())
                .add(BlockRegistry.STORAGE_FUNGAL_BRICKS.get())
                .add(BlockRegistry.STORAGE_MOSSY_STONE_BRICKS.get())
                .add(BlockRegistry.STORAGE_MUD_BRICKS.get())
                .add(BlockRegistry.STORAGE_NETHER_BRICKS.get())
                .add(BlockRegistry.STORAGE_PRISMARINE_BRICKS.get())
                .add(BlockRegistry.STORAGE_PURPUR_BLOCK.get())
                .add(BlockRegistry.STORAGE_QUARTZ_BRICKS.get())
                .add(BlockRegistry.STORAGE_RED_NETHER_BRICKS.get())
                .add(BlockRegistry.STORAGE_STONE_BRICKS.get())
                .add(BlockRegistry.STORAGE_TUFF_BRICKS.get())
                .replace(false);

        tag(TagRegistry.BONKABLE_BLOCKS)
                .addTag(TagRegistry.INVISIBLE_QUESTION_BLOCKS)
                .addTag(TagRegistry.QUESTION_BLOCKS)
                .addTag(TagRegistry.STORAGE_BRICK_BLOCKS)
                .add(BlockRegistry.POLISHED_AMETHYST.get())
                .add(BlockRegistry.POLISHED_AMETHYST_SLAB.get())
                .add(BlockRegistry.POLISHED_AMETHYST_STAIRS.get())
                .add(BlockRegistry.POLISHED_AMETHYST_WALL.get())
                .add(BlockRegistry.POLISHED_DEEP_FUNGAL_STONE.get())
                .add(BlockRegistry.POLISHED_DEEP_FUNGAL_STONE_SLAB.get())
                .add(BlockRegistry.POLISHED_DEEP_FUNGAL_STONE_STAIRS.get())
                .add(BlockRegistry.POLISHED_DEEP_FUNGAL_STONE_WALL.get())
                .add(BlockRegistry.POLISHED_FUNGAL_STONE.get())
                .add(BlockRegistry.POLISHED_FUNGAL_STONE_SLAB.get())
                .add(BlockRegistry.POLISHED_FUNGAL_STONE_STAIRS.get())
                .add(BlockRegistry.POLISHED_FUNGAL_STONE_WALL.get());

        tag(BlockTags.MINEABLE_WITH_PICKAXE)
                .addTag(TagRegistry.BONKABLE_BLOCKS)
                .addTag(TagRegistry.BRICK_PEDESTAL_BLOCKS)
                .addTag(TagRegistry.GOAL_POLE_BLOCKS)
                .addTag(TagRegistry.INVISIBLE_QUESTION_BLOCKS)
                .addTag(TagRegistry.QUESTION_BLOCKS)
                .addTag(TagRegistry.SMASHABLE_BLOCKS)
                .addTag(TagRegistry.STORAGE_BRICK_BLOCKS)
                .addTag(TagRegistry.WARP_PIPE_BLOCKS)
                .add(BlockRegistry.AMETHYST_BRICK_SLAB.get())
                .add(BlockRegistry.AMETHYST_BRICK_STAIRS.get())
                .add(BlockRegistry.AMETHYST_BRICK_WALL.get())
                .add(BlockRegistry.AMETHYST_BRICKS.get())
                .add(BlockRegistry.AMETHYST_BUTTON.get())
                .add(BlockRegistry.AMETHYST_PRESSURE_PLATE.get())
                .add(BlockRegistry.AMETHYST_SLAB.get())
                .add(BlockRegistry.AMETHYST_STAIRS.get())
                .add(BlockRegistry.AMETHYST_WALL.get())
                .add(BlockRegistry.CHISELED_AMETHYST_BRICKS.get())
                .add(BlockRegistry.COIN.get())
                .add(BlockRegistry.CRACKED_AMETHYST_BRICKS.get())
                .add(BlockRegistry.DEEP_FUNGAL_BRICK_SLAB.get())
                .add(BlockRegistry.DEEP_FUNGAL_BRICK_STAIRS.get())
                .add(BlockRegistry.DEEP_FUNGAL_BRICK_WALL.get())
                .add(BlockRegistry.DEEP_FUNGAL_BRICKS.get())
                .add(BlockRegistry.DEEP_FUNGAL_STONE.get())
                .add(BlockRegistry.DEEP_FUNGAL_STONE_BUTTON.get())
                .add(BlockRegistry.DEEP_FUNGAL_STONE_PRESSURE_PLATE.get())
                .add(BlockRegistry.DEEP_FUNGAL_STONE_SLAB.get())
                .add(BlockRegistry.DEEP_FUNGAL_STONE_STAIRS.get())
                .add(BlockRegistry.DEEP_FUNGAL_STONE_WALL.get())
                .add(BlockRegistry.FUNGAL_STONE.get())
                .add(BlockRegistry.FUNGAL_STONE_BUTTON.get())
                .add(BlockRegistry.FUNGAL_STONE_PRESSURE_PLATE.get())
                .add(BlockRegistry.FUNGAL_STONE_SLAB.get())
                .add(BlockRegistry.FUNGAL_STONE_STAIRS.get())
                .add(BlockRegistry.FUNGAL_STONE_WALL.get())
                .add(BlockRegistry.POLISHED_AMETHYST.get())
                .add(BlockRegistry.POLISHED_AMETHYST_SLAB.get())
                .add(BlockRegistry.POLISHED_AMETHYST_STAIRS.get())
                .add(BlockRegistry.POLISHED_AMETHYST_WALL.get())
                .add(BlockRegistry.POLISHED_DEEP_FUNGAL_STONE.get())
                .add(BlockRegistry.POLISHED_DEEP_FUNGAL_STONE_SLAB.get())
                .add(BlockRegistry.POLISHED_DEEP_FUNGAL_STONE_STAIRS.get())
                .add(BlockRegistry.POLISHED_DEEP_FUNGAL_STONE_WALL.get())
                .add(BlockRegistry.POLISHED_FUNGAL_STONE.get())
                .add(BlockRegistry.POLISHED_FUNGAL_STONE_SLAB.get())
                .add(BlockRegistry.POLISHED_FUNGAL_STONE_STAIRS.get())
                .add(BlockRegistry.POLISHED_FUNGAL_STONE_WALL.get())
                .replace(false);
    }
}